### ISSUE TITLE
Expanding sql engines

### ISSUE THREAD

**Issue by alofgreen** [vmware-archive/sql_magic#12]
Would it be beneficial to expand the sql engines used.  For example, using pyhive or pyodbc instead of Spark to pull from HIVE.

**Comment by scottcode** [comment]
sql_magic should already be capable of querying Hive using JDBC/ODBC,
thanks to the sqlalchemy integration. I think you'd just have to do
sqlalchemy's create_engine using the right prefix for the connection
string. If you have installed pyhive then an example connection string is
found in the link. It shouldn't require any changes to sql_magic itself.

https://github.com/dropbox/PyHive/issues/61

**Comment by alofgreen** [comment]
Thank you @scottcode this is really helpful.  Having some config. challenges with sqlalchemy but this works!

**Comment by scottcode** [comment]
Glad to hear it!

**Comment by scottcode** [comment]
Hopefully this resolves the original intent of the issue you posted, @alofgreen, so I'll close it. Just let me know if you feel it needs to be reopened, or if you have a more specific issue/request you are welcome to create a new issue. Thanks.
